### PR TITLE
Add kinetic to the list of indexed distros

### PR DESCRIPTION
**Pull request by jacquelinekay**
to be merged after ros/rosdistro#10443

### CODE REVIEW

**Comment by wjwwood** [comment]
+1

Can it not already be merged? I think the wiki is resilient to the fact that Kinetic was not yet in the rosdistro.

**Comment by dirk-thomas** [comment]
Yes, this can be deployed anytime.

**Comment by jacquelinekay** [comment]
Alright then, I'll merge it now so that we don't forget later. :)

**Comment by dirk-thomas** [comment]
This still needed to be deployed on the webserver. Done now.

**Pull request merged**
