### PR TITLE
Add statuspage embed content.

### PR DESCRIPTION
**Pull request by tfoote**
They have a new popup embed that should improve visibility in the case of an outage.

### CODE REVIEW

**Comment by tfoote** [comment]
There looks to have been a hiccup loading this content: https://discourse.ros.org/t/ros-wiki-page-is-too-heavy/10637

**Comment by peci1** [comment]
> There looks to have been a hiccup loading this content: https://discourse.ros.org/t/ros-wiki-page-is-too-heavy/10637

I'm having the problem in Firefox on Linux. Did you test this configuration?

**Comment by peci1** [comment]
Chromium loads fine.

**Comment by tfoote** [comment]
My default is chromium but I booted up firefox specifically to test. 

Screenshot from 2019-09-11 11-20-11

**Comment by peci1** [comment]
The last commit didnt help.

**Comment by tfoote** [comment]
Yeah, I didn't think it would change much but it's better practice to defer the loading. 

Can you see if you have a problem in a private browsing mode with your addons disabled? Maybe there's some interference?

**Comment by peci1** [comment]
Private window also has the problem. 

Error: Script terminated by timeout at:
clampTitle@https://rhybxq8cmnsd.statuspage.io/embed/frame?location=http%3A%2F%2Fwiki.ros.org%2F:248:32
init@https://rhybxq8cmnsd.statuspage.io/embed/frame?location=http%3A%2F%2Fwiki.ros.org%2F:163:11
@https://rhybxq8cmnsd.statuspage.io/embed/frame?location=http%3A%2F%2Fwiki.ros.org%2F:292:9
frame:248:32

**Comment by peci1** [comment]
Error: Failed to fetch https://rhybxq8cmnsd.statuspage.io/embed/frame?location=http%3A%2F%2Fwiki.ros.org%2F. Code 2147500036.
Stack: onResponse@resource://devtools/shared/DevToolsUtils.js:566:16
onStopRequest@resource://gre/modules/NetUtil.jsm:128:9
Line: 566, column: 16

**Comment by peci1** [comment]
This construct from embed/frame seems to be quite the possible candidate:

        clampTitle = function() {
          var div = document.querySelector('.incident-title')
          var p = document.querySelector('.incident-title p');
          var divHeight = div.clientHeight;
          while (p.clientHeight > divHeight) {
            var text = p.innerHTML;
            p.innerHTML = text.replace(/\W*\s(\S)*$/, '...'); // replace last word with ...
          }
        }

**Comment by peci1** [comment]
```
document.querySelector('.incident-title')
<h1 class="incident-title">

var div = document.querySelector('.incident-title')
      var p = document.querySelector('.incident-title p');
      var divHeight = div.clientHeight;
undefined
divHeight
18
p.clientHeight
19
```

**Comment by peci1** [comment]
So, at least in my case, p.clientHeight is still higher than divHeight.

**Comment by peci1** [comment]
I've asked statuspage.io to join this conversation.

**Comment by tfoote** [comment]
Well this was more of a pain than I'd hoped. If people are having issues it's not worth debugging into anymore. We already have the link at the top so I'll just close it out. Maybe it will work better if we try again in the future.

Thanks for trying things out @peci1

**Comment by peci1** [comment]
Thanks for fixing the issue. Although it's a pity you had to remove it...

**Comment by tfoote** [comment]
Hopefully we'll come back to it in the future after it's more mature. Early adoption has it's costs.

**Pull request closed without merging**
