### PR TITLE
Added robot images

### PR DESCRIPTION
**Pull request by esteve**
This adds the robot pictures from http://wiki.ros.org/Robots as static files.

### CODE REVIEW

**Comment by wjwwood** [comment]
+1, but this will be a potentially temporary improvement, because if the original authors ever change their image, I bet they'll use attachments again.

**Comment by dirk-thomas** [comment]
Why not put the images on download.ros.org? I would assume hosting them on a plain Apache is much more efficient then serving them through the wiki.

**Comment by esteve** [comment]
They will be served by Apache, but instead of just uploading them manually, I added the images to the roswiki repo, much like what we already do with many other images:

https://github.com/ros-infrastructure/roswiki/tree/master/custom/images

**Comment by tfoote** [comment]
+1

**Comment by gavanderhoorn** [comment]
Does this require updating the Robots page to not use `attachment:` as well?

**Comment by esteve** [comment]
@gavanderhoorn Yep, I was going to do that after this gets merged and deployed.

**Comment by esteve** [comment]
Merged and deployed, I'll update the wiki page now.

**Comment by esteve** [comment]
The wiki page is now using the static images, it's missing an image for the Cyton Gamma because the external link no longer works, I'll contact Energid and see if they can provide one.

**Pull request merged**
