### PR TITLE
update jenkins job links to support full urls

### PR DESCRIPTION
**Pull request by dirk-thomas**
@esteve @tfoote @wjwwood Please review and deploy.

### CODE REVIEW

**Comment by wjwwood** [comment]
+1

**Comment by esteve** [comment]
+1

**Comment by tfoote** [comment]
+1

**Comment by esteve** [comment]
Deployed.

**Comment by dirk-thomas** [comment]
Fixed JavaScript not handling urls with a trailing slash correctly.

**Pull request merged**
