### PR TITLE
Alert users to the ROS 2 Developers Guide.

### PR DESCRIPTION
**Pull request by kscottz**
If applied will alert users to ROS 2 developers guide. 

Unclear how to test this. Any suggestions?

### CODE REVIEW

**Comment by tfoote** [comment]
This is a dismissable alert box box that we usually reserve for temporary alerts. I think we probably actually want something persistent for this information.

There's a testing vagrant config here: https://github.com/ros-infrastructure/roswiki

**Comment by dirk-thomas** [comment]
I also don't think that we should point to the developer guide. The [landing page](https://index.ros.org/doc/ros2/) looks much more appropriate to me.

**Comment by tfoote** [comment]
I moved this to be persistent in the sidebar and updated the link to be the rolling page.

**Comment by tfoote** [comment]
@kscottz I can't assign you a review because you created this and I pushed on top of yours for expediency.

**Comment by kscottz** [comment]
So... just merge it? It has been a minute.

**Review by tfoote — APPROVED** [review]
If it looks good to you a merge is good. I've validated it and it's running already on the server. I'll merge it and deploy the committed version.

**Comment by kscottz** [comment]
Go ahead and deploy.

**Pull request merged**
