### PR TITLE
Removing old macros that refer to unavailable resources

### PR DESCRIPTION
**Pull request by tfoote**
code.ros.org, kforge.ros.org, photos.willowgarage.com are all invalid resources now.

Also clearing old work on Metrics that would probably be better to integrate into another area in the future. 

Also a PDF exporter macro that's not used but was an experiment in exporting wiki pages to PDF.

And clearing a reminant test macro.

Gist with searches for macro usages: https://gist.github.com/tfoote/e5adeca7bd918bf6bcb11d31ce2547a7 that would be great to clean up too, but will now just render with the macro calling text instead of blanks or errors.

### CODE REVIEW

**Comment by dhood** [comment]
I removed reference to the broken Ticket, TracLink and KforgeTracLink macros on the WikiMacros page in http://wiki.ros.org/action/info/WikiMacros?action=diff&rev2=82&rev1=81

Even though we don't use the RobotEntry / RobotTable macros on the Robots page anymore they're still used by translations e.g. http://wiki.ros.org/ko/Robots so it seems premature to remove them unlike the broken ones. If we want to remove them, is there a practice for communicating this change to translation maintainers or anything?

**Comment by tfoote** [comment]
The whole point of disabling the Robots page was to decrease the load caused by rendering the Robots macros. 

That "translated" page only has translated headers at the top and it has some outdated version of the Robots page from 2015 when it was copied and looks like it only had one update. If anything it should have been done with some includes to keep it up to date. All the automatic links were broken too, since the macros assumed root level, unless there was a translation of each individual robot's page for which non of the ones I tested had valid links.

I've changed it to a redirect to `/Robots` which has the deprecation message.

**Comment by dhood** [comment]
OK, then +1 to removing those macros.

The forwarding to robots.ros.org isn't done by the contents of the wiki.ros.org/Robots page, right? I was going to update the contents of http://wiki.ros.org/action/show/Robots (now that the new page has been released) but wanted to double check there isn't anything magic in the contents.

**Comment by tfoote** [comment]
The redirect to robots.ros.org is an Apache directive that url matches wiki.ros.org/Robots If you dismiss the preview/redirect notice or go to the page directly (instead of using the show action) it redirects. So you're free to change anything there.

**Pull request merged**
