### PR TITLE
Add melodic to the wiki.

### PR DESCRIPTION
**Pull request by clalancette**
Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
:+1: to confirm everything is working as expected.
Though that means we should allocate time soon to hide EOL distros https://github.com/ros-infrastructure/roswiki/pull/204

**Comment by dhood** [comment]
can you do the equivalent of this change too please: https://github.com/ros-infrastructure/roswiki/pull/199/files#diff-341a3118916c3daca1f33b898ac77d7eR54

**Comment by clalancette** [comment]
> can you do the equivalent of this change too please: https://github.com/ros-infrastructure/roswiki/pull/199/files#diff-341a3118916c3daca1f33b898ac77d7eR54

I didn't actually understand that bit.  What is that supposed to signify?  Am I just supposed to change it to `n-turtle`?

**Comment by dhood** [comment]
yeah people shouldn't be using `m-turtle` anymore because it has a name, but people will be allowed to use `n-turtle` if they want

**Comment by mikaelarguedas** [comment]
> can you do the equivalent of this change too please: https://github.com/ros-infrastructure/roswiki/pull/199/files#diff-341a3118916c3daca1f33b898ac77d7eR54


Yeah I thought about it, I didnt comment as I wasn't sure if it would make more sense to do it now or when we make the distro the default one.

**Comment by clalancette** [comment]
I ended up adding it now.  I'm also happy to revert; just let me know.

**Comment by mikaelarguedas** [comment]
LGTM, Leaving it up to @dhood to approve / merge / deploy

**Pull request merged**
