### PR TITLE
Update for new whitelist request issue

### PR DESCRIPTION
**Pull request by tfoote**
We maxed out the number of comments on an issue at 2500 so I created a new issue for requesting.

Now using #258

### CODE REVIEW

**Comment by tfoote** [comment]
@engr-sas please comment on #258 not here.

**Comment by louielinchichen** [comment]
Please add my username louielinchichen for access to the ROS wiki, thanks.

**Comment by muratkayamurat** [comment]
Hello There can you add "Murat" username to the whitelist. Thanks.

**Comment by lpyao** [comment]
Please add my username "lpyao" for access to the ROS wiki

**Comment by mostafa-IK03** [comment]
Hello please can you add "mostafa-IK03" to the ROS wiki

**Pull request merged**
